manager: support xz compression modules
Some modules using XZ for compression,
We should compat in manager too,
because ksud already support that

Fix the issue as below:
java.util.zip.ZipException: invalid compression method
  	at java.util.zip.ZipInputStream.read(ZipInputStream.java:254)
  	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:158)
  	at b21.q(r8-map-id-66ef10c51ecfe9c3f387d28e99856215b8f56ac8e1f78a1cb281ae59b988ab2e:443)
  	at kw.p(r8-map-id-66ef10c51ecfe9c3f387d28e99856215b8f56ac8e1f78a1cb281ae59b988ab2e:8)
  	at vu0.run(r8-map-id-66ef10c51ecfe9c3f387d28e99856215b8f56ac8e1f78a1cb281ae59b988ab2e:114)
  	at wi2.run(r8-map-id-66ef10c51ecfe9c3f387d28e99856215b8f56ac8e1f78a1cb281ae59b988ab2e:4)
  	at x95.run(r8-map-id-66ef10c51ecfe9c3f387d28e99856215b8f56ac8e1f78a1cb281ae59b988ab2e:3)
  	at zl0.run(r8-map-id-66ef10c51ecfe9c3f387d28e99856215b8f56ac8e1f78a1cb281ae59b988ab2e:88)

This fixed latest LSPosed-IT can't parse information by manager

Signed-off-by: AlexLiuDev233 <wzylin11@outlook.com>